In [7]:
##the siamese resnet
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from torch.utils.data import Dataset,DataLoader
import torchvision.transforms as transforms
from torch.autograd import Variable
import cv2
import numpy as np
import os
import random
import sys
import torchvision.models as models
import torch.optim as optim
import logging
import time
import warnings
import torch.nn.functional as F
from tensorboardX import SummaryWriter
import os
import skimage
from skimage import io
import shutil

In [ ]:
dirpath = './imagenet_fgsm/imagenet/fgsm/'
src_path = './imagenet_sample_train/'
for r,d,f in os.walk(dirpath):
    for file in f:
        if '.png' in file :
            print(file)
            print(file.split('_'))
            print(file.split('_')[1])
            print(file.split('_')[2])
            name = file.split('_')[1]+'_'+file.split('_')[2]
            new_path = shutil.copy(src_path+file.split('_')[1]+'/'+name+'.JPEG',dir_path+'fgsm_'+name+'_'+file.split('_')[3]+'_'+file.split('_')[3]+'.png')
            print(new_path)
        #break
    #break
    


In [76]:
dirpath = './imagenet_fgsm/imagenet/fgsm/'
files = []
for r,d,f in os.walk(dirpath):
    for file in f:
        if '.png' in file and 'checkpoint' not in file:
            files.append(dir_path+file)

print(len(files))

print(files[0])
random.shuffle(files)
print(files[0])
count = 0
with open('./fgsm_train.txt', 'w') as filehandle:
    for listitem in files[:1500]:
        filehandle.write('%s\n' % listitem)
        count +=1
print(count)


count = 0
with open('./fgsm_val.txt', 'w') as filehandle:
    for listitem in files[1500:1700]:
        filehandle.write('%s\n' % listitem)
        count +=1
print(count)

count = 0
with open('./fgsm_test.txt', 'w') as filehandle:
    for listitem in files[1700:]:
        filehandle.write('%s\n' % listitem)
        count +=1
print(count)


2000
./imagenet_fgsm/imagenet/fgsm/fgsm_n01664065_16537_33_33.png
./imagenet_fgsm/imagenet/fgsm/fgsm_n12267677_1282_988_937.png
1500
200
300


In [31]:
 with(open('./fgsm_val.txt')) as f:
            lines = f.readlines()
            for i in lines:
                print(i.rstrip())
                #print(i.split('_')[-2])
                break

./imagenet_fgsm/imagenet/fgsm/fgsm_n09332890_21158_975_912.png


tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         ...,
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         ...,
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357]],

        [[-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
         [-1.8044, -1.8044, -1.8044,  ..., -1

In [51]:
data['img2']

tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         ...,
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         ...,
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357]],

        [[-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
         [-1.8044, -1.8044, -1.8044,  ..., -1

In [52]:
data['img3']

tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         ...,
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         ...,
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357]],

        [[-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
         [-1.8044, -1.8044, -1.8044,  ..., -1

In [54]:
data['label2']

1